#!/usr/bin/env bun
/**
 * Generate FEATURE_MAP.md from the real filesystem (modules ∩ features ∩ contract).
 */
import { existsSync, readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

const root = join(import.meta.dir, '..')

const PLATFORM_MODULES = new Set(['health', 'pubsub'])

function listDirs(path: string): string[] {
  if (!existsSync(path)) return []
  return readdirSync(path, { withFileTypes: true })
    .filter((d) => d.isDirectory() && !d.name.startsWith('.'))
    .map((d) => d.name)
    .sort()
}

function contractFiles(): string[] {
  const dir = join(root, 'shared/contract/src')
  if (!existsSync(dir)) return []
  return readdirSync(dir)
    .filter((f) => f.endsWith('.ts') && !f.endsWith('.test.ts') && f !== 'index.ts')
    .map((f) => f.replace(/\.ts$/, ''))
    .sort()
}

const modules = listDirs(join(root, 'backend/modules'))
const features = listDirs(join(root, 'frontend/src/features'))
const contracts = contractFiles()

const productModules = modules.filter((m) => !PLATFORM_MODULES.has(m))

const lines: string[] = [
  '# FEATURE_MAP',
  '',
  '> Auto-generated by `bun run feature:map`. Do not edit by hand.',
  `> Generated: ${new Date().toISOString()}`,
  '',
  '## Product slices (expected mirror)',
  '',
  '| Domain | Backend module | Frontend feature | Contract file | Wired in app.ts | Wired in App.tsx |',
  '| ------ | -------------- | ---------------- | ------------- | --------------- | ---------------- |',
]

const appTs = existsSync(join(root, 'backend/src/app.ts'))
  ? readFileSync(join(root, 'backend/src/app.ts'), 'utf8')
  : ''
const appTsx = existsSync(join(root, 'frontend/src/App.tsx'))
  ? readFileSync(join(root, 'frontend/src/App.tsx'), 'utf8')
  : ''

const allProductNames = new Set([...productModules, ...features])

for (const name of [...allProductNames].sort()) {
  const beModule = name === 'auth' ? 'users' : name
  const be = productModules.includes(beModule) ? '✅' : '❌'
  const fe =
    features.includes(name) || (name === 'users' && features.includes('auth')) || name === 'auth'
      ? '✅'
      : '❌'
  // users domain maps to auth on FE and user.ts contract
  const aliases: Record<string, string> = {
    users: 'user',
    auth: 'user',
    notifications: 'notification',
  }
  const preferred = aliases[name] ?? name.replaceAll('-', '')
  const contractName = contracts.includes(preferred)
    ? preferred
    : (contracts.find((c) => c === name || name.replaceAll('-', '').includes(c)) ?? '—')
  const contractOk = contractName !== '—' ? '✅ `' + contractName + '.ts`' : '❌'
  const wiredBe =
    appTs.includes(`modules/${beModule}`) ||
    appTs.includes(`${beModule}Module`) ||
    (beModule === 'users' && appTs.includes('usersModule'))
      ? '✅'
      : '❌'
  const wiredFe =
    appTsx.includes(`features/${name === 'users' ? 'auth' : name}`) ||
    appTsx.includes(`/${name}`) ||
    (name === 'users' || name === 'auth'
      ? appTsx.includes('features/auth') || appTsx.includes('/login')
      : false)
      ? '✅'
      : '❌'

  lines.push(
    `| \`${name}\` | ${be} \`modules/${beModule}\` | ${fe} | ${contractOk} | ${wiredBe} | ${wiredFe} |`
  )
}

lines.push(
  '',
  '## Platform modules (no FE feature required)',
  '',
  ...[...PLATFORM_MODULES].map((m) => `- \`${m}\` → \`backend/modules/${m}\``),
  '',
  '## Notes',
  '',
  '- Product domain **users** uses frontend feature **`auth`** (session UI) + contract **`user.ts`**.',
  '- New product domains: `bun run slice:new <name>` then `bun run feature:done <name>`.',
  '- Canonical golden path: **notifications** (contract → module → feature → E2E smoke).',
  ''
)

const out = join(root, 'FEATURE_MAP.md')
writeFileSync(out, lines.join('\n'))
console.log(`Wrote ${out}`)
